aws:
  access:
    keyId: ${AWS_KEY_ID:fakeid}
    secret: ${AWS_SECRET:fakeSecret}
  dynamo:
    region: ${AWS_DYNAMO_REGION:sa-east-1}
    endpoint: ${AWS_DYNAMO_ENDPOINT:dynamodb.sa-east-1.amazonaws.com}
