package com.ada.dynamo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.util.UUID;

@Data
@DynamoDBTable(tableName = "quadros")
public class Quadro {
    @DynamoDBHashKey
//    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBRangeKey
    private String tipo;
    private String nome;
}
