package com.ada.dynamo.model;


import com.ada.dynamo.util.autogenerate.LocalDateTimeAutoGenerate;
import com.ada.dynamo.util.converter.LocalDateTimeToStringConverter;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.time.LocalDateTime;
import java.util.UUID;

@DynamoDBTable(tableName = "tarefas")
@Data
public class Tarefa {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private UUID id;
    private String titulo;
    private String descricao;
    @DynamoDBTypeConvertedEnum
    private Prioridade prioridade;
    @DynamoDBTypeConverted(converter = LocalDateTimeToStringConverter.class)
    @DynamoDBAutoGenerated(generator = LocalDateTimeAutoGenerate.class)
    private LocalDateTime criacao;
    @DynamoDBTypeConverted(converter = LocalDateTimeToStringConverter.class)
    private LocalDateTime previsao;
    @DynamoDBTypeConverted(converter = LocalDateTimeToStringConverter.class)
    private LocalDateTime conclusao;
}
